# Generated by Django 3.1.4 on 2020-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSUser',
            fields=[
                ('tag_no', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('flipkart_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('amazon_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('is_authy_verified', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('FLIPKART_ORDER_GETTING_CANCELLED', 'FLIPKART_ORDER_GETTING_CANCELLED'), ('NOT_ABLE_TO_LOGIN_FLIPKART', 'NOT_ABLE_TO_LOGIN_FLIPKART'), ('NOT_ABLE_TO_LOGIN_EMAIL', 'NOT_ABLE_TO_LOGIN_EMAIL')], default='ACTIVE', max_length=255)),
            ],
        ),
    ]
