ACTIVE = "ACTIVE"
FLIPKART_ORDER_GETTING_CANCELLED = "FLIPKART_ORDER_GETTING_CANCELLED"
NOT_ABLE_TO_LOGIN_FLIPKART = "NOT_ABLE_TO_LOGIN_FLIPKART"
NOT_ABLE_TO_LOGIN_EMAIL = "NOT_ABLE_TO_LOGIN_EMAIL"
USER_CURRENT_STATUS_TYPES = [
    ACTIVE,
    FLIPKART_ORDER_GETTING_CANCELLED,
    NOT_ABLE_TO_LOGIN_FLIPKART,
    NOT_ABLE_TO_LOGIN_EMAIL,
]
USER_CURRENT_STATUS_CHOICES = [(a, a) for a in USER_CURRENT_STATUS_TYPES]
